### ISSUE TITLE
Student account disappears while syncing

### ISSUE THREAD

**Issue by mdhuse** [operepo/ope#100]
This has happened several times now. I have gotten back a laptop that is not showing the student account. An instructor informed me that while the laptop was syncing the OPE LMS app  the laptop shutoff and when it came back on the students account would not show on the login screen. Re-credentialing the laptop would display the student again.

Ray correct me if I am off on this - I think what is happening is that the version is 1.0.108 and the student is logged in and the update to version 1.0.109 starts to run so the student account gets disabled. But the update can't fully complete resulting in the students account remaining disabled.

**Comment by frankyrumple** [comment]
Mike - you are correct - if for some reason the update doesn't finish properly, it will leave the student account disabled.  A blue screen, powering off, etc... would leave it half updated.

Solutions at that point are:
- Re-credential  OR
- Run the mgmt command to lock the machine back down (  mgmt lock_machine ).  That should re-apply security and enable the student account again.

A am going to create a seperate enahcement to better detect a failed update and re-run it so that if a shutdown happens, it would try to re-apply the update/security/etc...

**Comment by mdhuse** [comment]
Update - Thought that the reason the student account was disappearing was that they were logged in at the time of the update. Just got a notice that after restarting the laptop before the update to make sure the student was not logged in and running the update it still had not displayed the students account after the update.

**Comment by frankyrumple** [comment]
Thinking your catch on the gpupdate getting stuck might be the culprit. Released 1.0.13 for testing by John that should fix this. Will keep you posted.

**Comment by jmichel-sbctc** [comment]
Doesn't seem to be an issue anymore with the most recent releases that are available v: 1.0.118.

Closing the issue as this seems to be resolved once the full update has been applied.
